services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: urbanmind-zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: urbanmind-kafka

    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: urbanmind-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://urbanmind-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    ports:
      - "19092:9092"

  urbanmind:
    build: .
    container_name: urbanmind-dashboard

    depends_on:
      - kafka

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    restart: always